image: "python:3.7.3-stretch"

before_script:
  - pip install numpy scipy Pillow imageio opencv-python==3.4.2.17 opencv-contrib-python==3.4.2.17

test:
  script:
    - cd tests
    - chmod +x test.sh
    - ./test.sh
